### ISSUE TITLE
can you export the sql file for the database 

### ISSUE THREAD

**Issue by rashedomar** [TranPhucVinh/smart-home-php#1]
can you export the sql file for the database

**Comment by TranPhucVinh** [comment]
When having the cpanel of the host in byethost, you can import the .sql database from phpMyadmin of apache.

Thanks

**Comment by rashedomar** [comment]
Sure I know this steps but you’re not included the sql file that i will import

**Comment by TranPhucVinh** [comment]
I have update the .sql database.
Thanks for your concern
